#!/bin/bash

set -e

echo "Running Nymph Testing"
echo "Use \`run coverage\` to build coverage clover."
echo

if [[ "$1" == "coverage" ]]; then
	CVG="-coverage"
else
	CVG=""
fi

cd $(dirname $0)

if [[ "$DB" == "" || "$DB" == "mysql" ]]; then
	./run-mysql$CVG
fi
if [[ "$DB" == "" ]]; then
	echo -e "\n\n"
fi
if [[ "$DB" == "" || "$DB" == "pgsql" ]]; then
	./run-postgresql$CVG
fi

