#!/bin/bash

set -e

cd $(dirname $0)

if [[ "$DB" == "" || "$DB" == "mysql" ]]; then
	./run-mysql
fi
if [[ "$DB" == "" ]]; then
	echo -e "\n\n"
fi
if [[ "$DB" == "" || "$DB" == "pgsql" ]]; then
	./run-postgresql
fi

