#!/bin/bash

echo "################################################################################"
echo "#                         Running tests for PostgreSQL                         #"
echo -e "################################################################################\n"

phpunit --bootstrap bootstrapPostgreSQL.php tests
